{% set name = "django-material" %}
{% set version = "1.7.1" %}
{% set sha256 = "77cfcc83da7724066b5b78bbb72cd4fbe752b38ffb20cb6ca36feb9657d9f19f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django >=1.8

about:
  home: http://forms.viewflow.io/
  license: BSD 3-Clause

  # License not in current tarball. Including manually for now.
  # https://github.com/conda-forge/staged-recipes/pull/3159#pullrequestreview-45483471
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Material Design for django forms and admin
  description: |
    Django-Material offers an alternative approach to rendering forms in django.
    Strong Python/HTML code separation keeps your code DRY and free from underlying
    HTML/CSS rendering details. Field rendering customization happens in a template,
    not in code. Layouts allow setting relative location and size of fields.
  doc_url: http://docs.viewflow.io/material_forms.html
  dev_url: https://github.com/viewflow/django-material

extra:
  recipe-maintainers:
    - cshaley
