{% set name = "django-material" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-material-{{ version }}.tar.gz
  sha256: 5e3b9b6c67bd7013d08c879d1a18729015d826109d498c8079cb220e3d96de8e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<4.0
    - django >=2.2
    - six

test:
  imports:
    - material
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - django
    - six

about:
  home: http://forms.viewflow.io/
  license: BSD-3-Clause
  
  # License not in current tarball. Including manually for now.
  # https://github.com/conda-forge/staged-recipes/pull/3159#pullrequestreview-45483471
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  
  summary: 'Material Design for django forms and admin'
  description: |
    Django-Material offers an alternative approach to rendering forms in django.
    Strong Python/HTML code separation keeps your code DRY and free from underlying
    HTML/CSS rendering details. Field rendering customization happens in a template,
    not in code. Layouts allow setting relative location and size of fields.
  doc_url: http://docs.viewflow.io/material_forms.html
  dev_url: https://github.com/viewflow/django-material

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
