travis:
  secure:
    BINSTAR_TOKEN: t1w4+8/z6GUQ4V6A3XmLyVhwYwCAXuvscbZujKkI4k7a7FXkmb0GCTf28A7qVv9woybvMxFOrcKzeIJPzYMAaih1NatQcMpC0SvbsI/aR4XNnmWPieAzV6mh8Tin6KWSw4GW2ZLaPbJy38hTMaQ5L3gHSdRr16+zxB6qQeCngRHhe1h8wRwScCKgl8QpU+zoMZRiwxx4A4MvJEptrYSytBvna9GMRerOJyr9rSU4OET6+JGmfBU1RmSNNWm5uIRpWBUG77n9CLFVxXvLlmMVHlFBGbC88raHGw2jHFR+/iVGXhGI29S5M/AGH+q3uwz/KZtF9raietgZbyrgJAuMqsGoltwxG2z2BmxxZNZNJxvZHYVSDLUzQYfCOJ5Wp8F7eom1v5mKDGndqFdFMyPHtUmk045E/z6r7hn4AWBJci2/jBSLcW5c8fUWVcBuxsLEEQe0/bTOUlyGFEXpdTmBTztChW6Uj3+jADGiCPX9N5MRpDYm4GOBbBCSnTTEP1L/rBaJZPWWRPvizwuxC3bynmA0A/h9o9M1Un5bT8/iegEh8iJJlGAVXTRDwTfgNfMObAVYp0VhzbDQSL1/Fb0sMJg4bf8K29WR/ABSRMRxUykFJX6hBCgcKwtGf2bRgB/PU86dudlXe5AS8yd9wYvh7z7OhHysc19ob7xp1rIEyLM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
