travis:
  secure:
    BINSTAR_TOKEN: cxtDhmdYLarFIgS8N+LwBZx8SMzq0lwa5TZD6dGa7zDUbQthBc685dXtgNvpbaZBTvAqWc6+2wZ1h9BkBH0GYHJeVuZJG7+Zd5quHfDJ+4LNmYFoEH/+EDcJj41Bl6Gc4fjPOhM1Fijp32zrLM6yNfMWGbL2vdaOTpNqD6q39cJFQ/yPD84WZWX4i2gZUc1EeCvbIDIbeBt8V20SiFYWAs7wKp0dSLJdmSEoHJsSOmLC7RMUrobREeWK1+Z098EIaif6QCLgmb/lVEIGMT4fJyutqA9mLu57B0Rdk48BxLVMqFzr1EyOyaFx2PhbnA8ZLm85VPK7Sbp9PMus7PkLW11D1sEgGTNv0/msvScrR7lZdjmUAjABlthsnmpu3Qxn4PxmfndyOoKHP0qc7wBmJWDzaChzzMy3ZaSGo8OvDBiU48/ZMjDGTV7AXiCo14LKYpL8sdcHefUYKd0prlmZn1ukdI70A29YsGN/Bi/leYnH3wMTssKyAWurCxyL81pKcMJr4iGj+PPwQ3OG9XlHL68UANv0gU2WN6Iad0HS9kVrRHkHaFuKaPAy9WaCcFftHM52JxoppSPANMmDAcLq5IpfeQ0qDACCF10F2PMk7pD95jSMCt+0k4upbQaacwTPDP3tKy2nlONsLL3BQUG9ZTmeK5c0Bpza5f87ftJY+QE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
